config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    'One Star': '1_star',
    'Two Stars': '2_stars',
    'Three Stars': '3_stars',
    'Four Stars': '4_stars',
    'Five Stars': '5_stars'
  }

  validates :message, :rating, presence: true
  
  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver_now
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :place

  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
    paginates_per 10

    belongs_to :user
    has_many :comments
    has_many :photos
    
    geocoded_by :address
    after_validation :geocode
    
    validates :name, :address, :description, presence: true

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places
  has_many :comments
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def index
    @places = Place.order(:name).page(params[:page])
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end



  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: "You cannot edit other people's places!", status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: "You cannot edit other people's places!", status: :forbidden
    end

    @place.update_attributes(place_params)

    if @place.valid?
      redirect_to place_path(params[:id]) #I wanted it to link back to the edited place, not to the full index. How else will the user see if their edit went through easily?
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: "You cannot edit other people's places!", status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end


  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end



private



end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<!-- Button trigger modal -->


<!-- Modal -->


  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <span class="welp-w">W</span>elp.
      <% end %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
     

      <% if user_signed_in? %>

          <%= link_to  new_place_path, data: {toggle: 'modal', target: '#addPlace'}, class: 'nav-item nav-link' do %>
            <i class="fa fa-plus-circle"></i>
            New Place
            <% end %>

      <% else %>
        <div class="col-lg-10 mx-auto"></div> <!-- this is to fill in the gap between logo and login when user isn't logged in, in order to hide new place button -->
      <% end %>

    <div class="modal fade" id="addPlace" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content new-box">
          <div class="modal-header d-flex">
            
              <div class="close-box">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
            <div class="modal-header-title mx-auto">
              <h4 class="modal-title" id="myModalLabel">Enter your new place!</h4>
            </div>
          
        </div>
          <br />
            
              <%= simple_form_for Place.new do |f| %>
                <%= f.input :name %>
                <%= f.input :address %>
                <%= f.input :description, :as => :text, :input_html => {:rows => 3} %>
                <br />
                <%= f.submit 'Create', class: 'btn btn-primary center' %>
              <% end %>
             
        </div>
      </div>
    </div>

            
          
          <!--####### LOG IN BUTTONS ###### -->
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="user-email">
                Signed in as <%= current_user.email %>
              </li>
              <li>
                <%= link_to 'My Profile', user_path(current_user), class: 'btn btn-secondary sign-out' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-secondary sign-out' %>
              </li>
            <% else %>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle float-right" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Log in!
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary login-dropdown' %>
                  <br />
                  <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary login-dropdown' %>
                </div>
              </div>
            <% end %>
          </ul>
        </div>
                   </div>
      </nav>
      
      <% if notice.present? %>
        <p class="alert alert-info fade-in col-4 offset-4"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger col-4 offset-4"><%= alert %></p>
      <% end %>

    <%= yield %>

  </body>
</html> 

app/views/places/edit.html.erb
<div class="new-box col-10 offset-1 text-center">
<h1>Edit your place</h1>
<br />
<%= simple_form_for @place do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description, :as => :text, :input_html => {:rows => 3} %>
  <br />
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/places/index.html.erb


<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'Slider1.jpg', class: "d-block img-fluid" %>
      <div class="carousel-caption d-none d-md-block">
        <h2>Amazing eats, amazing people</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'Slider2.jpg', class: "d-block img-fluid" %>
      <div class="carousel-caption d-none d-md-block">
        <h2>Find your new go-to</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider3.jpg', class: "d-block img-fluid" %>
      <div class="carousel-caption d-none d-md-block">
        <h2>Food, and a view? Yes please.</h3>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!-- PAGINATION BUTTONS -->

<div class="d-flex justify-content-center page-buttons">
  <%= paginate @places %>
</div>

<!-- Place Display -->

<div class="container">
  <div class="row cards">
    <% @places.each do |place| %>

      <div class="booyah-box col-sm-5 col-12">
        <h1 class="place-name"><%= link_to place.name, place_path(place) %></h1>
        <i class="place-addy"><%= place.address %></i>
        <% if place.photos.present? %>
          <%= image_tag place.photos.first.picture.url, class: 'image-resize d-block img-fluid' %>
        <% end %>
        <br />
        <p class="place-disc"><%= place.description %></p>


        <!-- Last Comment -->
        <% if place.comments.present? %>
        <hr />
          <div class= "col-12">
            <blockquote>
              <% if place.comments.last.humanized_rating.present? %>
                <b class="rating-placement"><%= place.comments.last.humanized_rating %></b> -
              <% end %>
              <%= place.comments.last.message %>
              <small class="float-right">-<%= place.comments.last.user.email %></small>
            </blockquote>
          </div>
        <% end %>



      </div>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-center page-buttons">
  <%= paginate @places %>
</div> 
<div id="footer">
  <div class="container text-center">
    <div class="row">
      <div class="col-12 col-sm-6">
        <b>Contact</b>
        <br />
        joshua.bangle@gmail.com
      </div>
      <div class="col-12 col-sm-6 socials">
        <b>Social</b>
        <br />
        <%= link_to 'https://github.com/joshua-bangle' do %>
          <span class="fa fa-github-square fa-3x"></span>
        <% end %>
        <%= link_to 'https://twitter.com/KnoobLord' do %>
        <span class="fa fa-twitter-square fa-3x"></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/places/new.html.erb
<div class="new-box col-6 offset-3 text-center">
<h1>Enter Your Place Deets</h1>
<%= simple_form_for @place do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description, :as => :text, :input_html => {:rows => 3} %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div> 

app/views/places/show.html.erb
<div class="container">
  <div class="row">
  <div class="new-box col-5 ml-auto mr-auto">
    <div class="float-right">  
      <% if current_user && current_user == @place.user %>
        <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary edit-btn' %>
        <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
      <% end %>  
    </div>
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br /><br />
  <p><%= @place.description %></p>


  <% if @place.latitude.present? && @place.longitude.present? %>
      <script>

        function initMap() {
          var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

          var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 18,
            center: myLatLng
          });

          var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'Hello World!'
          });
        }
      </script>
      <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBgEPDSqAvZgF0NebRIZJNUvtmLwJrLNPs&callback=initMap">
      </script>
      <div id="map"></div>
  <% end %>
  <br />

                     <!--Comment Field-->  
    <% if current_user %>
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#addComment">
        Add a comment!
      </button>
      <button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#photoModal">
        Add a photo!
      </button>
    <% else %>
      <h3>Log in to leave a comment!</h3>
    <% end %>
  </div>


  <!-- Photo Modal -->
  <div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content new-box">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add a photo</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
            <%= f.input :picture %>
            <%= f.input :caption, label: 'Caption your photo!' %>
            
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add your photo", class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <!-- Photo Data -->

      <%if @place.photos.present? %>
        <div class="col-5 new-box picture-box mx-auto">
          <% @place.photos.each do |photo| %>

            <ul>
            <li ><%= image_tag photo.picture.url, class: 'image-resize' %>
            <p><%= photo.caption %></p>
          </li>
          <hr />
        </ul>

          <% end %>
        </div>
      <% end %>


</div>

</div>
<!-- Modal -->
<div class="modal fade" id="addComment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content new-box mx-auto">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
          <%= f.input :message, label: 'Leave a comment!' %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Add your Comment", class: 'btn btn-primary' %>
      </div>  
      </div>
        <% end %>
    </div>
  </div>
</div>

<% if @place.comments.present? %>
  <h1 class="text-center">Comments</h1>
  <div class= "comment-box mx-auto text-center">
  <% @place.comments.each do |comment| %> 
  
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small> -<%= comment.user.email %></small>
      </blockquote>
      <hr/>
    <% end %>
  </div>
<% end %>
  <!-- Button trigger modal -->



app/views/users/show.html.erb
<div class="profile-box mx-auto">
  <div class="row">
    <div class="col-4 d-flex justify-content-center">
    <%= image_tag 'default_user.png' %>
    </div>
    <div class="col-8">
    <h1><%= @user.email %></h1>
    <h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
    <h4><%= @user.comments.count %> total comments </h4>
    <h4><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</h4>
    </div>
  </div>
  <div class= "clear"></div>
</div>

<br />

<!--User Comments -->
<h1 class="text-center">My Comments</h1>
<br />
<div class="new-box mx-auto">
<div class="row">
  <% @user.comments.each do |comment| %>

    <div class="col-12 col-sm-6 text-center">
      <h2><%= link_to comment.place.name, place_path(comment.place) %></h2>
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <p><%= comment.message %></p>
        <small class="comment-email"><%= comment.user.email %></small>
      </blockquote>

    </div>
  <% end %>
</div>
</div>

<!-- User Places -->
<br />
<h1 class="text-center">My Places</h1>
<br />
<div class="new-box mx-auto">
  <div class="row">
    <% @user.places.each do |place| %>
      <div class="col-12 col-sm-6 text-center places-spaces">
        <h2><%= link_to place.name, place_path(place) %> </h2>
        <h3><%= place.address %></h3>
        <h4><%= place.description %> </h4> 
      </div>
      <div class="col-12 col-sm-6">
        <% if place.photos.present? %>
          <%= image_tag place.photos.first.picture.url, class: 'img-fluid' %>
        <% end %>
        <hr />
      </div>

    <% end %>

  </div>
</div>